# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a3d70c3657c97f0d4b1f1a5e18eb81035f90fcca17c86ffc99c53e6e42687c259e429eddefe12ed1dbeac54a163c2b39175dad860773c28d87c3bc7dd1ccb91

test:
  secret_key_base: e3518261acce08d274f00854b4b217ed1a8c835292eb3e1674614b9b5632245bd394d72a79603e91d012f6decf0ebdc37be5ef88f080ba393650e29bb035bc41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
